gui:
  nerdFontsVersion: "3"
  theme:
    cherryPickedCommitFgColor:
      - "#7F0000"
    cherryPickedCommitBgColor:
      - "none"
    selectedLineBgColor:
      - white
  spinner:
    frames: ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]
git:
  branchLogCmd: git log --graph --abbrev-commit --decorate --date=format:'%Y-%m-%d %H:%M:%S' --format=format:'%C(bold blue)%>|(15)%h%C(reset) %C(white)[%ar]%C(reset) %C(dim white)%>|(45)%an%C(reset) %C(auto)%d%C(reset) %C(white)%s%C(reset)' --color=always
  allBranchesLogCmd: git log --graph --abbrev-commit --decorate --date=format:'%Y-%m-%d %H:%M:%S' --format=format:'%C(bold blue)%>|(15)%h%C(reset) %C(white)[%ar]%C(reset) %C(dim white)%>|(45)%an%C(reset) %C(auto)%d%C(reset) %C(white)%s%C(reset)' --all --color=always
