gui:
  nerdFontsVersion: "3"
  theme:
    cherryPickedCommitFgColor:
      - "#7F0000"
    cherryPickedCommitBgColor:
      - "none"
    selectedLineBgColor:
      - white
  spinner:
    frames: ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]
git:
  branchLogCmd: git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)' --color=always
  allBranchesLogCmd: git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)' --all --color=always
